apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:4.2-bionic
          command: ["mongod", "--replSet", "rs01", "--bind_ip_all"]
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
            - name: mongod-config
              mountPath: /etc/mongo
      volumes:
        - name: mongod-config
          configMap:
            name: mongod-config
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "slow"
        resources:
          requests:
            storage: 5Gi
