apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
  template:
    spec:
      containers:
        - name: rocketchat
          image: rocketchat/rocket.chat:3.2.2
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-0.mongodb:27017/rocket"
            - name: MONGO_OPLOG_URL
              value: "mongodb://mongodb-0.mongodb:27017/local?replSet=rs01"
            - name: PORT
              value: "3000"
            - name: ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: rocket-config
                  key: ROOT_URL
